### ISSUE TITLE
Directive attribute for swatch

### ISSUE THREAD

**Issue by jonasch** [buberdds/angular-bootstrap-colorpicker#110]
Hey,
I switched from another library, that has some layout issues in IE and Firefox within modal forms to your colorpicker and I am really satisfied. But I am missing one feature: kind of a swatch in the input, where you see the colortext also as colored preview.
like here:
![image](https://cloud.githubusercontent.com/assets/9671803/10391951/f8e4499c-6e82-11e5-902c-2da68c4807ca.png)

Or is this already implemented and I just dont get the correct attribute working?
Would be really nice to have that.
Cheers

**Comment by buberdds** [comment]
Hey, 

'Input group' is already in Bootstrap, all you have to do is to use selected color as background
example
```
<div class="input-group">
<span class="input-group-addon" style="background-color: {{hexPicker.color}}"></span>
<input colorpicker  type="text" ng-model="hexPicker.color"  type="text" class="form-control" id="inputGroupSuccess4" aria-describedby="inputGroupSuccess4Status">
</div> 
```
