### ISSUE TITLE
issues with input

### ISSUE THREAD

**Issue by Tr4v1s** [buberdds/angular-bootstrap-colorpicker#112]
i ran into some issues with input:
1) when the user is typing the value is reapplied so the cursor would always jump to the end of the input. this can be pretty annoying when trying to edit a value after selecting something close to what you want.
2) the spellcheck wasn't set to false for the input, so i would always get a red line under "rgba(..."

i fixed these issues and issued a pull request.

let me know if i can assist in any way.
thanks,
Travis

**Comment by buberdds** [comment]
valid points, thanks for PR
