### ISSUE TITLE
Error when using elements apart from inputs and buttons

### ISSUE THREAD

**Issue by JuanHB** [buberdds/angular-bootstrap-colorpicker#119]
When triggering the colorpicker from any kind of element that doesn't have the ````value=""```` attribute an Exception will be thrown. Here is a [codepen with the problem](http://codepen.io/JuanBiscaia/pen/Rraxyx).

Because here:
````javascript
//parse a string to HSB
        setColor: function (val) {
          val = val.toLowerCase();
````
To solve the problem, just change to this:
````javascript
//parse a string to HSB
        setColor: function (val) {
          val = (val) ? val.toLowerCase() : val;
````
Now you can use any element to trigger the colorpicker. Another [codepen with the solution](http://codepen.io/JuanBiscaia/pen/NxNYKR).

I've openned a PR witht he solution: [#118](https://github.com/buberdds/angular-bootstrap-colorpicker/pull/118)

**Comment by buberdds** [comment]
:+1:
