### ISSUE TITLE
Use license specification matching bowers spec/githubs suggestion

### ISSUE THREAD

**Issue by egore** [buberdds/angular-bootstrap-colorpicker#121]
Currently the license is not documented in bower.json. According to the spec (see https://github.com/bower/spec/blob/master/json.md) the bower.json should have a field

"license": "MIT"

Next to that the filename should be LICENSE.txt like suggested by github (see https://help.github.com/articles/open-source-licensing/#where-does-the-license-live-on-my-repository)

**Comment by buberdds** [comment]
No PR after a month, closing this issue.

**Comment by egore** [comment]
I'm very sorry that I'm not doing your work for you. If you want your project to show up on webjars.org I recommend fixing the issue described above.

I worked around the problem by using http://ruhley.github.io/angular-color-picker/ instead.
