### ISSUE TITLE
Can't bind an array of colors to more colorpickers using ng-repeat

### ISSUE THREAD

**Issue by fttx** [buberdds/angular-bootstrap-colorpicker#126]
I've this array:
`vm.colors = ['#ffffff', '#00ffaa']`

and i want to bind each element to one colorpicker.

I came up with this template:
```
{{ vm.colors | json }}
<div ng-repeat="color in vm.colors">
	{{ color }}
	<input colorpicker ng-model="color" />
</div>
```

The problem is that vm.colors elements don't get updated when one of the colorpicker changes its value, while, obviusly `{{ color }}` get updated.

If i refer directly to the array, like this: `<input colorpicker ng-model="vm.colors[$index]" />` the array gets updated, but as soon the mousedown occurs, the color picker closes automatically, even if the mouse button is still pressed, see here: http://g.recordit.co/YcGjnNmH6b.gif

Even using events is not possible to workaround this problem because each colorpicker has the same model name, in this case "color", and from there is not possible to understand which is the position of the colorpicker that triggered the event

EDIT:
I ended to use ng-change and update another array from there
 `<input colorpicker ng-model="color" ng-change="onColorChange($index, color)" />`

**Comment by buberdds** [comment]
Hey,
use array of objects instead of using array of strings:

```
      $scope.vm = {
        colors: [{value:'#ffffff'}, {value:'#00ffaa'}]
      };
```
and in your template:

```
<input colorpicker ng-model="color.value" />
```

**Comment by fttx** [comment]
It worked! Thanks

**Comment by buberdds** [comment]
cool, good luck with yout app :smile:
