### ISSUE TITLE
When Click on Colorpicker First Time Color.Value = Undefined

### ISSUE THREAD

**Issue by artforlife** [buberdds/angular-bootstrap-colorpicker#129]
I run the following code to see what the value of colors are. 

```
app.controller('ColorCode', function($scope)

	$scope.$on("colorpicker-selected", function (color) {
		console.log('Color changed to ' + color.name + ' ' + $scope.color);
	});
	
});
```

When I click on colorpicker for the first time and change its color selection, I get the following in the console.

> Color changed to colorpicker-selected undefined

Is this an expected behavior? Perhaps it would be good to include some color default. For now, I am solving this by assigning $scope.color = "#000000", where color is the ng-model name for the colorpicker.

**Comment by buberdds** [comment]
Hey, yes this is expected behavior. you need to initialize model in your scope.

**Comment by artforlife** [comment]
Is it also expected that this happens each time I click the button to call the colorpicker? That is, even without reloading the page, each first click I make trying to pick a color returns the previous value. The second click actually changes the color to the proper new value.

**Comment by DHoffm** [comment]
I'am experiencing the same behaviour. Only the second click seems to give the correct value.
