### ISSUE TITLE
colorpicker-selected returning wrong value

### ISSUE THREAD

**Issue by DHoffm** [buberdds/angular-bootstrap-colorpicker#134]
I ran into the same problem as described here https://github.com/buberdds/angular-bootstrap-colorpicker/issues/129.

I setup an example: http://codepen.io/anon/pen/wWYBEy

It seems that the colorpicker-selected always returns the last color not the current.

**Comment by DHoffm** [comment]
The only thing so far that worked for me was the following:
```
$scope.$watch(function() {
  return $scope.clusterWidgetColorpickerColor;
}, function(newVal, oldVal) {
  if (newVal !== oldVal) {
    // correct color from here
  }
}, true);
```

**Comment by patlux** [comment]
Avoid using the event for listening on changes. Use simply the angular way `ng-change`.

http://codepen.io/patlux/pen/dXQOXO
