### ISSUE TITLE
Not working colorpicker-with-input="true"

### ISSUE THREAD

**Issue by lukaszpaczos** [buberdds/angular-bootstrap-colorpicker#142]
Hi,

I used colorpicker on button element and everything works fine, but problem is that on another element than input I cannot see template with input, even if I use colorpicker-with-input="true". That works only with input. 

When I analize colorpicker code I discover than when you change in colorpicker directive restrict from 'A' to 'AE' then colorpicker-with-input="true" works fine with another elements than input :)

I tested on 3.0.25, so can you please change bootstrap-colorpicker-module.js line 266 restrict from 'A' to 'AE'?

Best regards

**Comment by buberdds** [comment]
imo button and colorpicker-with-input="true" combo works fine

```
<button class="btn btn-success" colorpicker colorpicker-with-input="true" type="button" ng-model="hexPicker.color">Change Color</button>
```

**Comment by vishalthakur91** [comment]
i m working on same but i need user manually   input  color code in input box i am using it like this 
 '<colorpicker-preview style="height:21px; width: 22%; float: right; margin-top:0; margin-right: 11px;"></colorpicker-preview>' +
              '<input type="text">'+
and after that input is diplay in ui but able to add any type of input in input box
