### ISSUE TITLE
Import in a Webpack+babel stack

### ISSUE THREAD

**Issue by bernardocs** [buberdds/angular-bootstrap-colorpicker#147]
Hey...

I've been trying to use this library in my current structure (you can see it's boilerplate [here](https://github.com/AngularClass/NG6-starter)) with no success... 😞 

Tried 
```javascript
import 'angular-bootstrap-colorpicker';
```
, tried 
```javascript
import angular from 'angular';
import colorPicker from 'angular-bootstrap-colorpicker';

angular.module('app', [colorPicker]);
```
, and it fails to inject it... I `console.log()` it and it was an empty object `{}`...
Ah... I also tried all this with the css as well...
even tried a relative path directly to the JS file in the `node_module/`,
```javascript
// don't do this at home, kiddo...
import '../../node_modules/angular-bootstrap-colorpicker';
```
and nothing.

Not only I didn't found the root cause of it, but I also ran out of ideias.
Am I doing something wrong?

**Comment by buberdds** [comment]
Totally not related to the colorpicker module / closing.

**Comment by bernardocs** [comment]
Nevermind... In the light of not having a (proper) answer I figured it out myself...

Well... for those who got the same problem, just `import` the JS and the css like this:
```javascript
import angular from 'angular';
// ...
import 'angular-bootstrap-colorpicker';
import 'angular-bootstrap-colorpicker/css/colorpicker.css';
```
Doing such, webpack will put the JS at the vendor bundle and the CSS at `<head>`.
After that, just inject the colorpicker module as a dependency... so the whole thing would be like:
```javascript
import angular from 'angular';
import AnotherDependency1 from 'another-dependency-1';
import AnotherDependency2 from 'another-dependency-2';
import 'angular-bootstrap-colorpicker';
import 'angular-bootstrap-colorpicker/css/colorpicker.css';

angular.module('app', [
  AnotherDependency1,
  AnotherDependency2,
  'colorpicker.module'
]);
```
That worked out for me...
