### ISSUE TITLE
minified version doesn't work

### ISSUE THREAD

**Issue by nicdd** [buberdds/angular-bootstrap-colorpicker#149]
Everything works fine when I run the application locally, because it is served from a node server, not minified. On building as runnable spring-boot-jar, grunt minifies it. When I run the deployed version, I receive TypeErrors. 
First of all, when I let the cursor in the input field, as expected, the picker goes open but  the browser shows in the console:
TypeError: "a.on is not a function"
v()                                                                          vendors.6525b3ad.js:28
.link/<()                                                                   vendors.6525b3ad.js:28
defaultHandlerWrapper()                                       vendors.6525b3ad.js:1
createEventHandler/c()                                          vendors.6525b3ad.js:1

Then, when I am trying to pick a color, comes
 "d.setColor is not a function", 
and when I try to set the Hue,
 "d.setHue is not a function".

The close-button works normally.
I also have found on stackoverflow a very similar issue:

http://stackoverflow.com/questions/38906377/angular-bootstrap-colorpicker-is-not-working-in-minified-version

It would be great if anybody could solve this or give us a hint, what settings would be necessary in order to work properly. It also would be very useful if anybody would say if he/she could successfully use the min (bootstrap-colorpicker-module.MIN.js) version.

**Comment by buberdds** [comment]
Minified version is used in demo page and it works correctly. This repo is not handling custom builds issues.
