### ISSUE TITLE
Resizing Widget

### ISSUE THREAD

**Issue by NickPadilla** [buberdds/angular-bootstrap-colorpicker#39]
Hello, 

This is more of a question, or real issues with your module.  In fact it has worked really nicely.  However, I will be using this mainly - for now anyway - on mobile platforms.  So far it has worked really well but it is small and so difficult to really control it well.  I was wondering if there was a way to make the whole thing larger.  I think that would solve the problem with mobile platforms.  Please let me know if you have any guidance or thoughts. 

Thanks for a cool project!
Nick

**Comment by ArdentKid** [comment]
bump / +1 for sizing configuration as attribute

**Comment by jbonigomes** [comment]
+1 (config attribute)

**Comment by jbonigomes** [comment]
Is this option going to be added soon? Reason for my question is that I don't want to modify the core library, I am using it via Bower and have to deliver my project(using it) quite soon.

**Comment by valuka** [comment]
+1 Would love this feature in config, without needing to modify core lib.

**Comment by buberdds** [comment]
example 
colorpicker-size="200"

works only with px and it's affecting saturation panel only
