### ISSUE TITLE
Picker is not positioned correctly when used inside a scrollable container

### ISSUE THREAD

**Issue by jametsi** [buberdds/angular-bootstrap-colorpicker#46]
I have a div with max-height and overflow-y: scroll. Inside this div I have a table with colorpicker on one of its cells. The picker opens at correct position when the container is not scrolled, but if it is, the picker opens at the position where the cell would be if the container would be scrolled all the way to the top. I have tried this with colorpicker-fixed-position="true" and colorpicker-parent="true" without success.

**Comment by LudvikAdamec** [comment]
Hi, has anyone found a solution for placing colorpicker in scrollable div? Thanks

**Comment by jacobphillipsfs** [comment]
@mattsonic fix worked for me for both colopicker-parent = true and without that tag. @LudvikAdamec I recommend using his fix.

**Comment by buberdds** [comment]
If this is still not working correctly, please create a new issue. I think a few fixes were added in the meantime.
