### ISSUE TITLE
Selecting Colour with 2D slider jumps to red

### ISSUE THREAD

**Issue by Drammy** [buberdds/angular-bootstrap-colorpicker#50]
The colour picker jumps to red when dragging off the left or bottom limits of the picker.

Repro steps:
1. open the picker
2. select a green hue or any other than red
3. use the 2D slider to choose the colour's saturation
4. drag the slider out of the left hand or bottom boundary

result: the hue jumps to red.

**Comment by buberdds** [comment]
I don't know how and when, but this issue is resolved. If I'm wrong please re-open this issue.
