### ISSUE TITLE
Luminance

### ISSUE THREAD

**Issue by krigton** [buberdds/angular-bootstrap-colorpicker#58]
Recently I needed to restrict the picked colour to a certain luminance and I think It would be nice to have something like colorpicker-max-luminance, E.g. colorpicker-max-luminance="#555555", this would mean that the selected color cannot be more luminance than #555555.

I already forked the project and added this using the Digital CCIR601 formula (Y = 0.299 R + 0.587 G + 0.114 B) to calculate luminance. 

Let me know if you would like me to add this to the master.

Thank you.
.

**Comment by buberdds** [comment]
Thanks, I think there is no need for this feature in 'master' branch.
