### ISSUE TITLE
Colors leak between colorpicker instances when model is updated from other sources

### ISSUE THREAD

**Issue by ProdigySim** [buberdds/angular-bootstrap-colorpicker#65]
I've built a mostly stripped-down [codepen example](http://codepen.io/anon/pen/KwKVEX) where two colorpicker-enabled inputs sit on a page. The first input is just a normal colorpicker input. The second has its model color updated every second by a `$interval` callback.

I can produce "bleed" issues in two different ways on this page.

First:
1. Load the page and wait for the color of the second input to change automatically.
2. Click inside the first input to open colorpicker and note that the displayed color is not "pink".
3. Click outside the input and back in again to reopen colorpicker, and note that the color changes each time this is done.

Second:
1. Click inside the first input box to open colorpicker.
2. Hold down click in the colorpicker to slowly pick a color.
3. Keeping the mouse button held down, you will notice that every second the displayed color changes.

**Comment by reymarx** [comment]
Hi @buberdds I'm curious what's the status on this.

We want to be able to use multiple colorpickers in the same view.

thanks
