### ISSUE TITLE
Predefined colors

### ISSUE THREAD

**Issue by piernik** [buberdds/angular-bootstrap-colorpicker#75]
Cen You add predefined colors top pick with one click like in here http://bgrins.github.io/spectrum/ "Show Palette" section.

**Comment by michaeljota** [comment]
Have you tried to parse it as an option? 

```html

<li><spectrum-colorpicker ng-model="yourModel" options="{
    showPaletteOnly: true,
    showPalette:true,
    color: 'blanchedalmond',
    palette: [
        ['black', 'white', 'blanchedalmond',
        'rgb(255, 128, 0);', 'hsv 100 70 50'],
        ['red', 'yellow', 'green', 'blue', 'violet']
    ]
}" format="'rgb'"></spectrum-colorpicker></li>

```

This *should* work. As least is made to work like that.

**Comment by buberdds** [comment]
Hey, I will try to merge #68 today. Then you'll be able to create such pallete on you own

**Comment by jgribonvald** [comment]
Is there a way to purpose additionnaly pre-defined colors in some options for basic text color black or white ?
