### ISSUE TITLE
Position doesn't automatically changed

### ISSUE THREAD

**Issue by shreejibawa** [buberdds/angular-bootstrap-colorpicker#76]
I have uploaded issue demo here :  http://180.211.99.162/jt/omnistar/omnistar-widget/

Go to `Design Accordion` > Go to `Button Acordion` > Click on `Background Color` Input

This opens color picker at the very bottom of the page. Pre-computation of position affecting this one I assume.

**Comment by buberdds** [comment]
I assume this is deprecated,  I can see that you are using jQuery plugin to handle a color picker.
