### ISSUE TITLE
Toggle feature

### ISSUE THREAD

**Issue by anaisamp** [buberdds/angular-bootstrap-colorpicker#77]
Hi!
I have 6 colorpicker inputs in the same page.
I'm wondering if it's possible to have the inputs with a toggle behavior. I mean:
- In the first click the color picker opens.
- In the second click it closes if it's the same input. 
- Opens another color picker if I click in another input, just like it works now.

Is it possible?

Many thanks!

**Comment by buberdds** [comment]
Sorry I dont understand your case. so from my point of view it's not possible ;)

**Comment by anaisamp** [comment]
I managed achieve what I needed. I used the accordion widget from Bootstrap to expand/collapse the set of picker color. Thanks anyway!

Cheers,
Ana

**Comment by buberdds** [comment]
Great that you figure it out!
