### ISSUE TITLE
No events provided

### ISSUE THREAD

**Issue by dlinx** [buberdds/angular-bootstrap-colorpicker#79]
Please provide color picker events like, onchange, onselect, onopen,onclose

**Comment by buberdds** [comment]
There is ready to use emitEvent function to handle this. Now only 'colorpicker-closed' (onclose) event is emitted. I don't think we need to emit onchange or onselect within the color picker. You can handle this in your controller. I'm fine with onopen, so any PRs are welcome.

**Comment by buberdds** [comment]
thanks to  #85 we can close this issue.
