### ISSUE TITLE
Add the option for an on selected handler

### ISSUE THREAD

**Issue by ste2425** [buberdds/angular-bootstrap-colorpicker#83]
Been using this colour picker to allow the user to select a colour for a rendered chart. 

I was originally using the ng-change directive to tell the chart to re render when a colour was selected. Whilst this works, when moving dragging the cursor over the hue section (Think that is the correct name) it caused performance issues as the chart was re rendered on every mouse move event. 

This option would allow the chart to be re rendered only when the colour was actually selected.

This has been implemented in pull request #82

Edit: 
I apologise I did not see issue #72 when creating this. The PR may provide a solution there too.

**Comment by buberdds** [comment]
merged
