### ISSUE TITLE
Npm error

### ISSUE THREAD

**Issue by Kepro** [buberdds/angular-bootstrap-colorpicker#90]
Hi i try to install with npm but i get error

"npm http GET https://registry.npmjs.org/angular-bootstrap-colorpicker
npm http 404 https://registry.npmjs.org/angular-bootstrap-colorpicker
npm ERR! 404 'angular-bootstrap-colorpicker' is not in the npm registry.
"

**Comment by buberdds** [comment]
Can you check it now? I published the package one more time

**Comment by Kepro** [comment]
Yep, now working :) thanks for fast fix!

**Comment by buberdds** [comment]
np
