### ISSUE TITLE
Colorpicker doesn't work in Firefox

### ISSUE THREAD

**Issue by burakkilic** [buberdds/angular-bootstrap-colorpicker#93]
Hi;

I am using the code below:

    <div class="col-md-10">
          <div class="input-group color colorpicker-default">
                                        <input colorpicker colorpicker-with-input="true" type="text" ng-model="option.value" class="form-control" />
                                        <span colorpicker ng-model="option.value" class="input-group-btn" style="background-color: {{option.value}}; width:20px;"></span>
                                    </div>
                                </div>

In chrome, I can select colors from color-picker, but in Firefox, I cannot.

CSS and js files are loaded. Where am I wrong?

**Comment by buberdds** [comment]
hey can you download the latest version? Bugfix was released today, so maybe this case is already resolved.

**Comment by burakkilic** [comment]
I have 3.0.16. Which is the latest version?

**Comment by buberdds** [comment]
yep that is the latest version. I tested your example and it is working in FF, any more details?

**Comment by burakkilic** [comment]
Maybe it is because of the scripts include locations. I included:

      <link href="assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="lib/angular-bootstrap-colorpicker/css/colorpicker.min.css" rel="stylesheet" type="text/css" />

css like this. And js:
        <script src="lib/angular-bootstrap-colorpicker/js/bootstrap-colorpicker-module.js"></script>


between the head tags.

**Comment by buberdds** [comment]
I don't think so it's the case. can you upload your example somewhere? or create a codepen?

**Comment by PeterTim** [comment]
I've reproduced the problem in FF with bootstrap-colorpicker-module.min.js.  bootstrap-colorpicker-module.js works well.

**Comment by burakkilic** [comment]
Interesting. I'm using     <script src="lib/angular-bootstrap-colorpicker/js/bootstrap-colorpicker-module.js"></script>

**Comment by buberdds** [comment]
thanks @PeterTim, I forgot to run build after last PR, file updated

**Comment by Angel-AOL** [comment]
I met the same problem in FF today. 
Just copied the simplest color picker from CodePen
                    <div class="col-md-5">
                        <input colorpicker ng-model="hexPicker.color" type="text">
                    </div>
I am using the latest js file and it works fine in Chrome. But in FF, wherever I clicked inside the sliderSaturation, the color stuck to #000000.

Any idea what might happened?
![screen shot 2015-05-08 at 3 04 48 pm](https://cloud.githubusercontent.com/assets/10640586/7543603/de9eca34-f593-11e4-81ce-434c04c30f17.png)
![screen shot 2015-05-08 at 3 05 08 pm](https://cloud.githubusercontent.com/assets/10640586/7543605/dea88e7a-f593-11e4-90cd-b88c60aed03f.png)
![screen shot 2015-05-08 at 3 05 16 pm](https://cloud.githubusercontent.com/assets/10640586/7543604/dea78c50-f593-11e4-85dd-3a552a7836f0.png)

**Comment by llattes** [comment]
Submitted a PR with a possible fix for Firefox (Tested in FF 37.0.2). Feature still works in other major browsers.

**Comment by Angel-AOL** [comment]
It works. Thanks @llattes 
-Tested in FF 37.0.2 and other browsers(Safari Opera Chrome)

**Comment by llattes** [comment]
@Angel-AOL I submitted a new PR (#95) that does not depend on jQuery to do the trick. It should work like the previously suggested fix.

**Comment by buberdds** [comment]
Hey, #95 looks good for me in general, but I couldn't reproduce this bug in FF. @Angel-AOL can you confirm that #95 is OK? thanks

**Comment by Angel-AOL** [comment]
@llattes @buberdds 
I overwrote previous bootstrap-colorpicker-module.js with the new .js file to do the test. The bug re-appeared. Same as I described before. in FF 37.0.2.

**Comment by llattes** [comment]
@Angel-AOL Are you sure you grabbed the file with the changes corresponding to PR #95 ?
I experienced the same issue than you and with both fixes I suggested the bug is gone. Can you verify the .js you're testing has the following lines?
```javascript
// Polyfills for making https://github.com/buberdds/angular-bootstrap-colorpicker/issues/93 work properly
var offsetX = (event.offsetX || event.pageX - (event.target.offsetParent.offsetLeft + event.target.offsetLeft));
var offsetY = (event.offsetY || event.pageY - (event.target.offsetParent.offsetTop + event.target.offsetTop));
```

**Comment by llattes** [comment]
I re-tested the fix using several VMs and it worked fine. I tested combinations of Win 7/8 with IE11, FF 36, 37 and 38 Beta and Mac with FF 37 and Chrome and found no problems.
I also verified the output of the polyfill in Chrome and it returns the same value than `event.offsetX`.
Finally, I replaced my colorpicker (which uses options like `colorpicker-with-input="true" colorpicker-position="bottom"`) by the simple example @Angel-AOL provided (`<input colorpicker ng-model="hexPicker.color" type="text">`) and it worked too.
Sorry I insist with this, it's just that I forked the project to go live with this fix but would like to move back to the original project once a new release is shipped.
@burakkilic @PeterTim Could you also give the code in #95 a try?
Thanks!

**Comment by burakkilic** [comment]
Yes, it seems to work fine.Thank you.

**Comment by Angel-AOL** [comment]
@llattes Yes I included those lines. I copy/paste 
```
// Polyfills for making https://github.com/buberdds/angular-bootstrap-colorpicker/issues/93 work properly
var offsetX = (event.offsetX || event.pageX - (event.target.offsetParent.offsetLeft + event.target.offsetLeft));
var offsetY = (event.offsetY || event.pageY - (event.target.offsetParent.offsetTop + event.target.offsetTop));
```
to replace previous 
```
          var offsetX = (event.offsetX || event.pageX - $(event.target).offset().left);
          var offsetY = (event.offsetY || event.pageY - $(event.target).offset().top);
```
I am using it inside the modal component of angularUI bootstrap. Could it affect anything here?

my code is as below:
```
<div class="modal-body">
...
   <div class="col-md-5">
         <div style="position:relative">
         <input colorpicker colorpicker-parent="true" type="text" ng-model="show.pagebackground.color" style="width:100%"/>
       </div>
    </div>
```
Any idea?

**Comment by llattes** [comment]
@Angel-AOL I'm using the component inside a modal too but cannot tell if it could be affecting.
There's another way of calculating the offset, using the existing `getOffset` function that's located at the top of the module file. Maybe you can give it a try since it works for me in every browser too.
The idea is to replace the `offsetX` and `offsetY` variables with the following code:
```javascript
var offsetX = (event.offsetX || event.pageX - targetOffset.left);
var offsetY = (event.offsetY || event.pageY - targetOffset.top);
```
It's simpler to read and relies on existing code. It would be helpful if you can debug the code a bit with Firebug to see if you find something strange.
Thanks again!

**Comment by Kaisirak** [comment]
Actually the reason it doesn't work is because of the colorpicker-parent="true". It does work on Chrome, but somehow it doesn't on Firefox.

Do you have any idea how to make it work ?

**Comment by buberdds** [comment]
I hope it's fine now.

**Comment by llattes** [comment]
I'll give your change a try and get back to you soon!

**Comment by buberdds** [comment]
Thanks for your time and your help guys.
